- sympy/core/expr.py
- sympy/core/numbers.py
- sympy/core/tests/test_assumptions.py
- sympy/core/tests/test_relational.py
- sympy/functions/special/tests/test_gamma_functions.py
- sympy/integrals/transforms.py
an alternative to https://github.com/sympy/sympy/pull/9040
> Set zoo.is_complex to True and zoo.is_real to False

- sympy/printing/latex.py
- sympy/printing/pretty/pretty.py
- sympy/printing/pretty/tests/test_pretty.py
- sympy/printing/tests/test_latex.py
- sympy/series/limits.py
- sympy/series/tests/test_limits.py
see https://github.com/sympy/sympy/pull/8194
> Add support for bidirectional limits (dir="real")

- sympy/core/expr.py
- sympy/series/gruntz.py
- sympy/series/order.py
- sympy/series/tests/test_aseries.py
- sympy/series/tests/test_limits.py
- sympy/series/tests/test_order.py
see https://github.com/sympy/sympy/pull/8542
> MrvAsympt algorithm to find asymptotic expansion

- sympy/concrete/summations.py
- sympy/concrete/tests/test_sums_products.py
fix https://github.com/sympy/sympy/issues/5511
see https://github.com/sympy/sympy/pull/8267
> Implement findrecur (with Sister Celine's algorithm)

- doc/src/gotchas.rst
- doc/src/guide.rst
- sympy/core/__init__.py
- sympy/core/benchmarks/bench_basic.py
- sympy/core/operations.py
- sympy/core/singleton.py
- sympy/core/sympify.py
- sympy/functions/special/zeta_functions.py
- sympy/series/limits.py
Only sympy/core/core.py left...
> Removed few remaining C imports/exports, fix docs

- CONTRIBUTING.rst
> Add guidelines for contributing (CONTRIBUTING.rst)

- .travis.yml
- bin/test_travis.sh
- setup.cfg
- sympy/printing/tests/test_theanocode.py
- sympy/tests/test_wester.py
> Use py.test for regular tests and for slow tests

- sympy/integrals/heurisch.py
- sympy/tests/test_wester.py
> Use ordered set of monoms in heurisch

- doc/modules/core.rst
- sympy/abc.py
- sympy/core/core.py
- sympy/polys/polytools.py
- sympy/utilities/tests/test_pickling.py
Conflicts:
doc/src/gotchas.rst
sympy/core/singleton.py
sympy/core/sympify.py
sympy/functions/elementary/trigonometric.py
// fixed by skirpichev
> Removed last traces of sympy.core.core.C from SymPy

- .mailmap
- AUTHORS
- CONTRIBUTING.rst
- bin/mailmap_update.py
- doc/aboutus.rst
Reverts skirpichev/omg#62
Oh..
> Revert "Revert "Removing Kirill from credits.""

- sympy/series/order.py
- sympy/series/tests/test_nseries.py
- sympy/series/tests/test_order.py
> Fix O.contains expr.is_Add heuristics (was invalid for point != 0)

- sympy/functions/special/tests/test_zeta_functions.py
- sympy/functions/special/zeta_functions.py
- sympy/series/gruntz.py
- sympy/series/tests/test_gruntz.py
> Implement helper function _zetas to make zeta tractable by the Gruntz algorithm

- setup.py
- sympy/integrals/tests/test_failing_integrals.py
> Use py.test in setup.py

- doc/requirements.txt
- setup.py
- sympy/core/cache.py
> Try to preserve decorated signatures

- sympy/functions/elementary/exponential.py
- sympy/functions/elementary/tests/test_exponential.py
> Implement nseries helper for LambertW

- sympy/solvers/inequalities.py
- sympy/solvers/tests/test_inequalities.py
> Add a quick exit in _reduce_inequalities if inequality == True/False

- sympy/functions/elementary/tests/test_trigonometric.py
- sympy/functions/elementary/trigonometric.py
see https://github.com/sympy/sympy/pull/8454
a replacement for https://github.com/skirpichev/omg/pull/9
> Implement cot as a ReciprocalTrigonometricFunction

- sympy/functions/elementary/complexes.py
- sympy/series/tests/test_gruntz.py
- sympy/series/tests/test_nseries.py
partial fix for https://github.com/skirpichev/omg/issues/75
> Correct Abs._eval_nseries

- sympy/functions/elementary/piecewise.py
- sympy/functions/elementary/tests/test_piecewise.py
- sympy/integrals/integrals.py
- sympy/integrals/tests/test_integrals.py
- sympy/integrals/transforms.py
- sympy/polys/polyutils.py
- sympy/polys/tests/test_polyutils.py
- sympy/solvers/inequalities.py
- sympy/solvers/tests/test_inequalities.py
A better (I believe) alternative to @smichr's sympy/sympy#10205, no
special case for linear eqs.
> Remove _solve_inequality helper

- sympy/functions/combinatorial/factorials.py
- sympy/series/limits.py
- sympy/series/order.py
- sympy/series/tests/test_gruntz.py
- sympy/series/tests/test_order.py
> Add regression tests for some SymPy's bugs

- sympy/polys/polyutils.py
- sympy/polys/tests/test_polyutils.py
first commit - from sympy/sympy#10166
> Make parallel_poly_from_expr aware of unevaluated Mul

- sympy/core/expr.py
- sympy/core/power.py
- sympy/functions/elementary/exponential.py
- sympy/series/tests/test_demidovich.py
- sympy/series/tests/test_limits.py
- sympy/series/tests/test_nseries.py
I have a little speedup for tests in sympy/series (891 vs 622 sec) on my system,
> Major rewrite of ancient garbage in Pow._eval_nseries

- sympy/core/expr.py
- sympy/core/mul.py
- sympy/core/power.py
- sympy/core/tests/test_eval_power.py
- sympy/core/tests/test_expand.py
- sympy/core/tests/test_function.py
- sympy/functions/elementary/exponential.py
- sympy/functions/elementary/tests/test_integers.py
- sympy/functions/elementary/tests/test_piecewise.py
- sympy/functions/special/gamma_functions.py
- sympy/functions/special/tests/test_error_functions.py
- sympy/functions/special/tests/test_gamma_functions.py
- sympy/functions/special/tests/test_zeta_functions.py
- sympy/series/gruntz.py
- sympy/series/tests/test_gruntz.py
- sympy/series/tests/test_nseries.py
- sympy/series/tests/test_order.py
- sympy/series/tests/test_series.py
> Complete XPOS todo in Expr.series

- CONTRIBUTING.rst
c.f. sympy/sympy#10506 and sympy/sympy#10508
Наш ответ Чемберлену.
[skip ci]
> Adopt No Code Of Conduct

- sympy/core/expr.py
- sympy/core/function.py
- sympy/core/tests/test_eval_power.py
- sympy/core/tests/test_function.py
- sympy/functions/special/tests/test_error_functions.py
- sympy/series/residues.py
- sympy/series/tests/test_nseries.py
- sympy/series/tests/test_series.py
- sympy/tests/test_wester.py
Now all returned by Function.nseries terms are correct.
Fixes skirpichev/omg#210
Closes sympy/sympy#10503
> Function._eval_nseries: Drop heuristic prediction for number of terms

- README.rst
aboutus.rst is up to date for included commits, but
see skirpichev/omg#220
> Add link to aboutus.rst and note about LICENSE in README.rst

- sympy/simplify/radsimp.py
This add a more detailed explanation of expected input and
remove redundant note about expand.  I don't think, that this
helps people who don't read documentation at all, but I
believe this is better then before.
Problem refs:
https://groups.google.com/forum/?fromgroups=#!topic/sympy/Xt5841y57S0
> Improve collect() docstring

- docs/modules/numeric-computation.rst
- setup.py
- sympy/core/cache.py
- sympy/core/tests/test_cache.py
- sympy/external/tests/test_autowrap.py
- sympy/matrices/expressions/tests/test_matmul.py
- sympy/matrices/tests/test_matrices.py
- sympy/tests/test_wester.py
- sympy/utilities/autowrap.py
- sympy/utilities/tests/test_autowrap.py
> Use cachetools

- sympy/simplify/hyperexpand.py
- sympy/simplify/tests/test_hyperexpand.py
This alone could solve summation problem in skirpichev/omg#236, without using (not a bad idea anyway) gosper_sum first.
> Use limit in hyperexpand

- sympy/solvers/ode.py
- sympy/solvers/tests/test_ode.py
Now we don't assume that eqs are in explicit form,
i.e. resolved w.r.t. the highest derivatives.
> This should allow mass matrix in LODE

- .travis.yml
- conftest.py
- diofant/core/compatibility.py
- diofant/core/numbers.py
- diofant/core/tests/test_sympify.py
- diofant/external/importtools.py
- diofant/polys/domains/groundtypes.py
- diofant/printing/tests/test_repr.py
- diofant/series/tests/test_series.py
- diofant/solvers/tests/test_ode.py
- diofant/tests/test_wester.py
- setup.cfg
- setup.py
See https://github.com/diofant/diofant/pull/200 for previous attempt.
https://github.com/travis-ci/apt-source-whitelist/issues/237
> Use gmpy2, drop gmpy support

- diofant/core/assumptions.py
Now documentation is available for interactive sessions, not just in Sphinx.  I believe this is better.
> Add docstrings for assumptions to the Basic class

- .travis.yml
- docs/modules/numeric-computation.rst
See https://github.com/sympy/sympy/issues/11608 and https://github.com/sympy/sympy/issues/10134.
> Test Python 3.6

- diofant/matrices/__init__.py
- diofant/matrices/dense.py
- diofant/matrices/expressions/blockmatrix.py
- diofant/matrices/immutable.py
- diofant/matrices/matrices.py
- diofant/matrices/sparse.py
- docs/modules/matrices/sparse.rst
This could be a first step in making Matrix = ImmutableMatrix, see sympy/sympy#6509.
> Reorganise export of classes in the matrices submodule

- docs/_static/theme_overrides.css
- docs/conf.py
See snide/sphinx_rtd_theme#329
> Drop override theme.css

- diofant/core/function.py
- diofant/core/tests/test_function.py
- diofant/diffgeom/tests/test_diffgeom.py
@bojone, I believe this fixes your problem in sympy/sympy#11799
> Fix Subs derivative

- diofant/functions/elementary/piecewise.py
- diofant/functions/elementary/tests/test_piecewise.py
- diofant/printing/latex.py
- diofant/printing/pretty/pretty.py
- diofant/printing/tests/test_latex.py
- diofant/series/limits.py
- diofant/series/tests/test_limits.py
- docs/release/notes-0.9.rst
> Simplify Piecewise series by checking conditions at x = 0+

- diofant/concrete/tests/test_sums_products.py
- diofant/core/tests/test_arit.py
- diofant/core/tests/test_complex.py
- diofant/core/tests/test_equal.py
- diofant/core/tests/test_expr.py
- diofant/core/tests/test_match.py
- diofant/core/tests/test_numbers.py
- diofant/core/tests/test_subs.py
- diofant/functions/elementary/tests/test_complexes.py
- diofant/functions/elementary/tests/test_trigonometric.py
- diofant/integrals/tests/test_integrals.py
- diofant/matrices/tests/test_matrices.py
- diofant/plotting/tests/test_plot.py
- diofant/polys/polytools.py
- diofant/polys/tests/test_numberfields.py
- diofant/polys/tests/test_polytools.py
- diofant/printing/pretty/tests/test_pretty.py
- diofant/printing/tests/test_latex.py
- diofant/simplify/tests/test_radsimp.py
- diofant/simplify/tests/test_simplify.py
- diofant/simplify/tests/test_trigsimp.py
- diofant/solvers/polysys.py
- diofant/solvers/solvers.py
- diofant/solvers/tests/test_ode.py
- diofant/solvers/tests/test_polysys.py
- diofant/solvers/tests/test_solvers.py
- docs/release/notes-0.9.rst
> Filter out zeros in GroebnerBasis constructor

- diofant/combinatorics/graycode.py
- diofant/combinatorics/partitions.py
- diofant/combinatorics/permutations.py
- diofant/combinatorics/prufer.py
- diofant/core/basic.py
- diofant/core/function.py
- diofant/core/tests/test_args.py
- diofant/core/tests/test_count_ops.py
- diofant/diffgeom/diffgeom.py
- diofant/matrices/expressions/blockmatrix.py
- diofant/matrices/expressions/matexpr.py
- diofant/matrices/expressions/tests/test_matadd.py
- diofant/matrices/expressions/tests/test_matrix_exprs.py
- diofant/printing/latex.py
- diofant/printing/tests/test_latex.py
- diofant/printing/tests/test_octave.py
- diofant/simplify/tests/test_powsimp.py
- diofant/simplify/tests/test_simplify.py
- docs/release/notes-0.9.rst
> Make MatrixSymbol truly atomic, like Symbol

- diofant/calculus/optimization.py
- diofant/calculus/tests/test_optimization.py
- docs/release/notes-0.9.rst
> Linear optimization

- diofant/ntheory/factor_.py
- diofant/ntheory/residue_ntheory.py
- diofant/ntheory/tests/test_ntheory.py
> Improve ntheory test coverage up to 100%

- diofant/solvers/recurr.py
- diofant/solvers/tests/test_recurr.py
- docs/release/notes-0.9.rst
@klemvor, @pedritomelenas, let me know if you have some comments.
> rsolve_hyper: take into account degenerate solutions

- diofant/interactive/__init__.py
- diofant/interactive/printing.py
- diofant/interactive/session.py
- diofant/polys/densebasic.py
- diofant/polys/orderings.py
- diofant/polys/polyconfig.py
- diofant/polys/polyfuncs.py
- diofant/polys/polyutils.py
- diofant/polys/sqfreetools.py
- diofant/polys/tests/test_densebasic.py
- diofant/polys/tests/test_orderings.py
- diofant/polys/tests/test_polyconfig.py
- diofant/polys/tests/test_polyfuncs.py
- diofant/polys/tests/test_polyutils.py
- diofant/polys/tests/test_sqfreetools.py
- docs/install.rst
- docs/release/notes-0.9.rst
and improve test coverage for polys
> Improve installation docs

- diofant/functions/elementary/piecewise.py
- diofant/solvers/__init__.py
- diofant/solvers/inequalities.py
- diofant/solvers/solvers.py
- diofant/solvers/tests/test_inequalities.py
- diofant/solvers/tests/test_solvers.py
- docs/modules/solvers/inequalities.rst
- docs/release/notes-0.9.rst
> Use piecewise_fold args of piecewise when solving

- diofant/solvers/recurr.py
- diofant/solvers/tests/test_recurr.py
- docs/release/notes-0.9.rst
> More efforts to simplify inhomogenous term in rsolve_hyper

- diofant/core/add.py
- diofant/core/mul.py
- diofant/core/numbers.py
- diofant/polys/tests/test_numberfields.py
- diofant/printing/pretty/pretty.py
- docs/modules/polys/wester.rst
- docs/release/notes-0.9.rst
> Arithmetic ops on AlgebraicNumber's

- diofant/matrices/expressions/matmul.py
Unless I'm misunderstanding the code, this new comment is a more accurate description.
> clarify X*X.I rewrite rule

- diofant/concrete/gosper.py
- diofant/core/compatibility.py
- diofant/core/numbers.py
- diofant/integrals/risch.py
- diofant/polys/domains/__init__.py
- diofant/polys/domains/polynomialring.py
- diofant/polys/domains/pythonrationalfield.py
- diofant/polys/domains/tests/test_domains.py
- diofant/polys/domains/tests/test_gmpy.py
- diofant/polys/domains/tests/test_polynomialring.py
- diofant/polys/partfrac.py
- diofant/polys/polyroots.py
- diofant/polys/polytools.py
- diofant/polys/rootoftools.py
- diofant/polys/tests/test_polyroots.py
- diofant/polys/tests/test_polytools.py
- diofant/printing/latex.py
- diofant/printing/pretty/stringpict.py
- diofant/printing/pretty/tests/test_stringpict.py
- diofant/printing/str.py
- diofant/solvers/tests/test_recurr.py
- docs/release/notes-0.9.rst
> Remove Poly.get_domain, use Poly.domain property

- diofant/integrals/tests/test_integrals.py
- diofant/polys/solvers.py
- diofant/polys/tests/test_solvers.py
- docs/release/notes-0.9.rst
This problem triggered in heurisch.py by #478.
> solve_lin_sys: be sure that returned values are of ring.dtype

- diofant/domains/algebraicfield.py
- diofant/domains/domain.py
- diofant/domains/tests/test_domains.py
> Fix Domain.unify() for AlgebraicField's

- diofant/polys/rootoftools.py
- diofant/polys/tests/test_rootoftools.py
- diofant/printing/pretty/pretty.py
- diofant/printing/pretty/tests/test_pretty.py
- diofant/solvers/solvers.py
- diofant/solvers/tests/test_solvers.py
> Support subs for RootOf's with free symbols

- .travis.yml
see https://github.com/travis-ci/travis-ci/issues/5695
> Travis: use trusty image

- diofant/interactive/session.py
- diofant/interactive/tests/test_ipython.py
> Fix IntegerDivisionWrapper for negative rationals

- diofant/core/basic.py
- diofant/core/numbers.py
- diofant/core/tests/test_function.py
- diofant/core/tests/test_numbers.py
- diofant/matrices/immutable.py
- docs/release/notes-0.9.rst
> Return NotImplemented, not False, upon rich comparison with unknown type

- .travis.yml
See #518 and travis-ci/travis-ci#8162
> Revert "Travis: split more"

- diofant/functions/elementary/tests/test_trigonometric.py
- diofant/logic/algorithms/dpll.py
- diofant/logic/algorithms/dpll2.py
- diofant/logic/boolalg.py
- diofant/logic/tests/test_boolalg.py
- diofant/logic/tests/test_inference.py
- docs/modules/logic.rst
> 100% test coverage for logic module

- diofant/core/tests/test_expr.py
- diofant/solvers/solvers.py
- diofant/solvers/tests/test_solvers.py
- docs/modules/solvers/solvers.rst
- docs/release/notes-0.9.rst
cherry-picked changes from #542
> Improve interfaces of solve() and checksol()

- diofant/polys/rootoftools.py
- diofant/polys/tests/test_rootoftools.py
- docs/release/notes-0.9.rst
> Add ability to rewrite RootOf's with radicals

- conftest.py
- diofant/ntheory/tests/test_ntheory.py
- docs/release/notes-0.9.rst
- setup.py
https://hypothesis.readthedocs.io/en/latest/
> Use hypothesis

- .travis.yml
- docs/release/notes-0.9.rst
- setup.py
> Use xdist plugin for pytest

- diofant/functions/special/error_functions.py
- diofant/functions/special/tests/test_error_functions.py
- diofant/integrals/heurisch.py
- diofant/integrals/tests/test_integrals.py
- diofant/series/tests/test_limits.py
- docs/release/notes-0.9.rst
> Misc fixes

- diofant/simplify/tests/test_sqrtdenest.py
- diofant/solvers/solvers.py
- diofant/solvers/tests/test_ode.py
- diofant/solvers/tests/test_solvers.py
See diofant/diofant#464 and diofant/diofant#387
> Cleanup solve_linear

- .travis.yml
- diofant/core/numbers.py
- diofant/polys/numberfields.py
- diofant/polys/tests/test_groebnertools.py
- diofant/polys/tests/test_numberfields.py
- diofant/utilities/__init__.py
- docs/release/notes-0.7.4.rst
- docs/release/notes-0.9.rst
- setup.py
> Remove RuntimeError case from primitive_element()

- diofant/polys/factortools.py
- diofant/polys/tests/test_factortools.py
- diofant/polys/tests/test_polytools.py
- diofant/simplify/tests/test_simplify.py
- docs/release/notes-0.9.rst
Commit 02aecba was wrong, as it doesn't count multiplicities
of factors.  See https://groups.google.com/forum/#!topic/sympy/0tQhLXJn7cw
for an example of issue.  For another approach, see sympy/sympy#13198.
Fixes sympy/sympy#13149
Also, add regression tests for issues, fixed by 02aecba.
Closes sympy/sympy#9296
Closes sympy/sympy#9630
Closes sympy/sympy#12792
Closes sympy/sympy#12506
Closes sympy/sympy#13115
> Fix factorization in RR for non square-free polynomials

- diofant/polys/rootisolation.py
- diofant/polys/tests/test_rootisolation.py
- docs/release/notes-0.9.rst
> Roots isolation in the Gaussian rational domain

- diofant/polys/rootisolation.py
- diofant/polys/rootoftools.py
- diofant/polys/tests/test_rootoftools.py
> Support conjugation of RootOf's

- .travis.yml
- setup.cfg
https://docs.travis-ci.com/user/reference/xenial/#python-support
> Using dist:xenial in Travis CI

- diofant/domains/finitefield.py
- diofant/domains/integerring.py
- diofant/printing/pretty/pretty.py
- diofant/printing/str.py
- diofant/tests/domains/test_domains.py
- diofant/tests/printing/test_pretty.py
- docs/release/notes-0.10.rst
see https://github.com/sympy/sympy/issues/13886 and https://github.com/sympy/sympy/issues/9544
c.f. https://reference.wolfram.com/language/FiniteFields/tutorial/FiniteFields.html
> Finite fields for non-prime orders

- diofant/polys/polyutils.py
- diofant/polys/rootoftools.py
- diofant/tests/polys/test_rootoftools.py
- docs/release/notes-0.10.rst
> More careful sorting of conjugated polynomial roots

- .github/workflows/test.yml
- .travis.yml
> Replace Travis-CI by Github Actions (enable one)

- .github/workflows/test.yml
- diofant/tests/utilities/test_codegen.py
- diofant/utilities/codegen.py
- docs/release/notes-0.11.rst
port of https://github.com/sympy/sympy/pull/13184
> Codegen support cse

- diofant/solvers/ode.py
- diofant/tests/solvers/test_ode.py
- diofant/tests/solvers/test_solvers.py
- docs/tutorial/solvers.rst
> sysode_linear_neq_order1(): simple optimization

- diofant/polys/numberfields.py
- diofant/tests/polys/test_numberfields.py
> Drop unused is_isomorphism_possible() helper

- diofant/solvers/recurr.py
- diofant/tests/solvers/test_recurr.py
- diofant/tests/test_wester.py
- docs/release/notes-0.11.rst
- docs/tutorial/solvers.rst
- setup.cfg
Much likely 34bc2b7bb6 and a partial fix for diofant/diofant#931.
> Make list of dict's - default output for rsolve()

- diofant/solvers/deutils.py
- diofant/solvers/polysys.py
- diofant/solvers/solvers.py
- diofant/solvers/utils.py
- diofant/tests/core/test_expr.py
- diofant/tests/solvers/test_polysys.py
- diofant/tests/solvers/test_solvers.py
- docs/modules/solvers/utilities.rst
- docs/release/notes-0.11.rst
- docs/release/notes-0.9.rst
> solve() returns all roots for algebraic equations

- diofant/domains/finitefield.py
- diofant/polys/factortools.py
- diofant/polys/galoistools.py
- diofant/tests/polys/test_galoistools.py
- docs/internals/polys.rst
- docs/release/notes-0.11.rst
> Port galoistools module to use FF domains

- diofant/polys/compatibility.py
- diofant/polys/euclidtools.py
- diofant/polys/rings.py
- diofant/tests/polys/test_euclidtools.py
- docs/internals/polys.rst
- docs/release/notes-0.11.rst
- docs/sources.bib
> Port euclidtools to use sparse polys

- diofant/polys/euclidtools.py
- diofant/tests/integrals/test_risch.py
> Restore PolynomialRing._gcd_monom() helper

- diofant/polys/rings.py
- diofant/tests/polys/test_rings.py
- docs/internals/polys.rst
- docs/release/notes-0.13.rst
> Protect PolyElement's from being modified

- diofant/polys/sqfreetools.py
- diofant/tests/polys/test_sqfreetools.py
- docs/release/notes-0.13.rst
- docs/sources.bib
> polys: square-free factorization for multivariate polynomials over GF

- .github/workflows/test.yml
- conftest.py
- diofant/__main__.py
- diofant/tests/concrete/test_sums_products.py
- diofant/tests/test_cli.py
- docs/cli.rst
- docs/conf.py
- docs/index.rst
- docs/install.rst
- docs/release/notes-0.13.rst
- setup.cfg
> Console script

- diofant/core/expr.py
- diofant/core/mul.py
- diofant/tests/concrete/test_gosper.py
- diofant/tests/series/test_limits.py
- diofant/tests/series/test_residues.py
- diofant/tests/series/test_series.py
- diofant/tests/test_wester.py
- docs/release/notes-0.13.rst
This finally fix diofant/diofant#1139
Closes sympy/sympy#21176
> core: avoid deep expanding in Mul._eval_nseries()

- diofant/core/numbers.py
- diofant/diffgeom/diffgeom.py
- diofant/matrices/expressions/matexpr.py
- diofant/plotting/plot_implicit.py
- diofant/polys/polytools.py
- diofant/printing/codeprinter.py
- diofant/series/order.py
- diofant/solvers/diophantine.py
- diofant/solvers/pde.py
- diofant/stats/crv.py
- diofant/stats/rv.py
- diofant/tests/polys/test_polytools.py
- diofant/tests/printing/test_ccode.py
- pyproject.toml
- setup.cfg
> Reduce "pragma: no cover" usage

- diofant/series/gruntz.py
- diofant/series/limits.py
- diofant/tests/series/test_limits.py
- docs/release/notes-0.14.rst
> series: support Boolean limits

- diofant/integrals/rationaltools.py
- diofant/tests/integrals/test_rationaltools.py
- docs/release/notes-0.15.rst
Also add citation.
Closes sympy/sympy#25896
Closes diofant/diofant#1363
@smichr
> log_to_real: add missing roots in case C(r_u, v) == 0

- .github/workflows/publish.yml
- .github/workflows/test.yml
> Enable new GA workflow to publish package

- diofant/domains/mpelements.py
- diofant/domains/realfield.py
- diofant/tests/polys/test_factortools.py
- diofant/tests/polys/test_polytools.py
- diofant/tests/polys/test_rings.py
- diofant/tests/polys/test_rootoftools.py
- docs/release/notes-0.16.rst
> domains: use as_integer_ratio() to RR.to_rational()
