diofant/diofant

.travis.yml, setup.cfg, sympy/combinatorics/testutil.py, sympy/core/numbers.py, sympy/functions/special/error_functions.py, sympy/geometry/plane.py, sympy/integrals/prde.py, sympy/integrals/rde.py, sympy/integrals/risch.py, sympy/liealgebras/type_a.py, sympy/liealgebras/type_b.py, sympy/liealgebras/type_c.py, sympy/liealgebras/type_d.py, sympy/liealgebras/type_f.py, sympy/ntheory/residue_ntheory.py, sympy/physics/optics/medium.py, sympy/sets/tests/test_sets.py, sympy/simplify/simplify.py, sympy/solvers/inequalities.py, sympy/solvers/ode.py, sympy/solvers/pde.py, sympy/utilities/tests/test_code_quality.py
also, fix E111-E113 errors:
E111 - indentation is not a multiple of four
E112 - expected an indented block
E113 - unexpected indentation
=> Add pep8 config, use pep8 in travis

sympy/integrals/integrals.py, sympy/integrals/tests/test_integrals.py, sympy/series/order.py, sympy/series/tests/test_nseries.py, sympy/series/tests/test_order.py
It's not clear how to correct evaluation of derivatives for O exprs (see https://github.com/sympy/sympy/pull/2356), but it's clear that the current code is mathematically wrong.  Wrong code should be removed.
=> Don't evaluate derivatives for O expressions

sympy/core/add.py, sympy/core/basic.py, sympy/core/mul.py, sympy/core/numbers.py, sympy/core/operations.py, sympy/core/tests/test_arit.py, sympy/printing/pretty/pretty.py, sympy/printing/pretty/tests/test_pretty.py, sympy/printing/str.py, sympy/printing/tests/test_latex.py, sympy/printing/tests/test_str.py
```python
In [1]: Add(0, 0, evaluate=False)
Out[1]: 0 + 0
In [2]: Mul(1, 1, evaluate=False)
Out[2]: 1⋅1
In [3]: print(Add(0, 0, evaluate=False))
0 + 0
In [4]: print(Mul(1, 1, evaluate=False))
1*1
```
=> Keep trivial sums/products unevaluated

.mailmap, AUTHORS, CONTRIBUTING.rst, bin/mailmap_update.py, doc/aboutus.rst
This reverts commit d02eededb3836d577efe087c9a18b53009c22533.
I'm very positive about additional license restrictions for changes in this
fork (GPL or LGPL, see CONTRIBUTING.rst).  That's why I think I can
revert this shame from the project files.  Emails changed to follow @navytux account.
I hope, Kirill will be ok with all this.
=> Revert "Removing Kirill from credits."

sympy/series/limits.py, sympy/series/tests/test_limits.py
as_leading_term() method assume that argument is positive.
=> Fix skirpichev/omg#55

sympy/concrete/tests/test_gosper.py, sympy/core/expr.py, sympy/functions/combinatorial/factorials.py, sympy/functions/combinatorial/tests/test_comb_factorials.py, sympy/functions/combinatorial/tests/test_comb_numbers.py, sympy/series/gruntz.py, sympy/series/limits.py, sympy/series/tests/test_gruntz.py, sympy/series/tests/test_limits.py
=> Removed SubsSet in gruntz, use xreplace()

sympy/core/mul.py, sympy/core/tests/test_assumptions.py, sympy/plotting/tests/test_plot.py
See 
https://github.com/sympy/sympy/pull/9379
https://github.com/sympy/sympy/issues/8840
https://github.com/sympy/sympy/pull/9376
https://github.com/sympy/sympy/pull/9374
https://github.com/sympy/sympy/pull/9194
https://github.com/sympy/sympy/pull/9421
=> Misc no-cache fixes

sympy/simplify/powsimp.py, sympy/simplify/tests/test_powsimp.py
I don't understand this huge mess (i.e. powsimp) in details,
but this simple fix prevents a "simplification" like
In [1]: powsimp((-1)**(Symbol('n', odd=True)/2))
Out[1]: I
No action is ok here, but better would be I**n (like Mathematica).
Fixes skirpichev/omg#143
Fixes sympy/sympy#10195
=> Stop brave "simplifications" of complex powers with neg bases

sympy/concrete/expr_with_limits.py, sympy/core/basic.py, sympy/core/expr.py, sympy/core/relational.py, sympy/core/symbol.py, sympy/core/tests/test_args.py, sympy/core/tests/test_relational.py, sympy/functions/elementary/complexes.py, sympy/functions/elementary/integers.py, sympy/geometry/util.py, sympy/integrals/integrals.py, sympy/integrals/manualintegrate.py, sympy/integrals/rationaltools.py, sympy/matrices/tests/test_matrices.py, sympy/parsing/sympy_parser.py, sympy/plotting/experimental_lambdify.py, sympy/plotting/plot_implicit.py, sympy/polys/orderings.py, sympy/printing/latex.py, sympy/printing/pretty/pretty.py, sympy/printing/repr.py, sympy/series/order.py, sympy/solvers/inequalities.py, sympy/solvers/solvers.py, sympy/solvers/tests/test_inequalities.py, sympy/tensor/indexed.py, sympy/utilities/autowrap.py, sympy/utilities/codegen.py
see https://github.com/sympy/sympy/issues/7951 and https://bugs.python.org/issue22052
=> Fix "flip" of arguments in relational expressions

sympy/solvers/ode.py, sympy/solvers/tests/test_ode.py
The answer was deadly wrong.  x0 and y0 - are functions of t
in general (particular solution), but C2 - is not (arbitrary constant).
Perhaps, the later was a typo (missed *).
Reference: http://eqworld.ipmnet.ru/en/solutions/sysode/sode0107.pdf
=> Correct general case in _linear_2eq_order1_type7

docs/modules/vector/examples.rst, sympy/concrete/summations.py, sympy/concrete/tests/test_sums_products.py, sympy/core/symbol.py, sympy/core/tests/test_count_ops.py, sympy/core/tests/test_eval.py, sympy/core/tests/test_function.py, sympy/core/tests/test_symbol.py, sympy/matrices/tests/test_matrices.py, sympy/parsing/sympy_parser.py, sympy/printing/pretty/tests/test_pretty.py, sympy/simplify/tests/test_simplify.py, sympy/solvers/ode.py, sympy/solvers/tests/test_ode.py
See
https://groups.google.com/forum/?fromgroups=#!topic/sympy/Gn0d3Udb69I
Closes sympy/sympy#3539
=> Remove undocumented Symbol.__call__ helper

sympy/core/function.py, sympy/core/tests/test_args.py, sympy/diffgeom/diffgeom.py, sympy/functions/elementary/complexes.py, sympy/functions/special/tensor_functions.py, sympy/integrals/tests/test_failing_integrals.py, sympy/matrices/expressions/determinant.py, sympy/printing/mathematica.py, sympy/printing/tests/test_mathematica.py, sympy/stats/rv.py
=> Partial fix for sympy/sympy#4064

sympy/simplify/hyperexpand.py, sympy/simplify/tests/test_hyperexpand.py
This quick exit is not wrong, but redundant.  Meanwhile, there is a real bug (fixed with second commit):
```
In [1]: hyper((), (2,), 0)
Out[1]: 
┌─  ⎛  │  ⎞
├─  ⎜  │ 0⎟
0╵ 1 ⎝2 │  ⎠
In [2]: hyperexpand(_)
Out[2]: 0
In [3]: Out[1].n()
Out[3]: 1.00000000000000
```
Another problem:
```
In [1]: hyperexpand(hyper((), (2,), z))
Out[1]: 
⎛       ___⎞
besseli⎝1, 2⋅╲╱ z ⎠
───────────────────
___       
╲╱ z        
In [2]: _.subs(z, polar_lift(0))
Out[2]: 0
In [3]: a, b = Integer(0), polar_lift(Integer(0)); a/b
Out[3]: 0
```
Proper fix for this goes to https://github.com/skirpichev/omg/pull/235.
=> Revert redundant return statement, introduced in ea4ff5a

sympy/combinatorics/partitions.py, sympy/combinatorics/tests/test_partitions.py, sympy/sets/sets.py, sympy/sets/tests/test_sets.py, sympy/stats/rv.py, sympy/tests/test_wester.py
see https://github.com/sympy/sympy/pull/8508
a replacement for https://github.com/skirpichev/omg/pull/11 (travis-ci won't build old pr?)
I believe, we should be more careful for FiniteSet's with symbolic elements also in following cases:
```
In [1]: len(FiniteSet(x, y))
Out[1]: 2
In [2]: for i in FiniteSet(x, y):
...:     print(i)
...: 
x
y
```
We can iterate over this set only if elements are non-Symbols.
=> Improve evaluation of Intersection's for FiniteSet with symbolic elements

sympy/ntheory/residue_ntheory.py, sympy/sets/fancysets.py, sympy/sets/sets.py, sympy/sets/tests/test_fancysets.py, sympy/utilities/iterables.py, sympy/utilities/tests/test_iterables.py
Used in ProductSet.\__iter__ to fix sympy/sympy#10497
=> Cartesian product of iterables using Cantor pairing

sympy/solvers/ode.py, sympy/solvers/tests/test_ode.py
I hope @cbm755 ok if I continue [his work](https://github.com/sympy/sympy/pull/9235) here.
sysode_linear_order1_jordan -> sysode_linear_neq_order1
=> dsolve: expm/jordan solver

sympy/solvers/recurr.py, sympy/solvers/tests/test_recurr.py
Use rsolve_ratio instead.
Fixes diofant/diofant#294
Closes sympy/sympy#11261
Closes sympy/sympy#7055
=> Build correct inhomogeneous solution in rsolve_hyper

diofant/core/add.py, diofant/series/tests/test_limits.py
This also partially fix issues with
Add._eval_as_leading_term, mentioned by @jksuom.
Anyway, this expand_mul() call looks like a hack,
so I'll remove one.
Closes sympy/sympy#11526
=> Add regression test for sympy/sympy#11526

diofant/core/numbers.py, diofant/functions/elementary/complexes.py, diofant/functions/elementary/tests/test_complexes.py, diofant/functions/special/delta_functions.py, diofant/functions/special/tests/test_delta_functions.py, diofant/printing/tests/test_latex.py, diofant/stats/drv.py, diofant/stats/rv.py, diofant/tensor/indexed.py
List generated with ``git grep '^ *is_[a-z].*= '|egrep -v 'is_number|is_comparable|is_iterable|is_interval|is_open|is_linear|is_global|is_default|is_canon_|is_mat|is_conto|is_parame|is_impli|is_func|is_contr|is_newz|is_arg|is_group|is_symbol|is_equal|is_cycle|is_slice|is_str' | cut -f1 -d:|sort|uniq | xargs -n1 -I {} printf " - [ ] {}\n"``
=> Check & fix explicit assumption properties (i.e. is_real = False)

conftest.py, diofant/core/basic.py, diofant/interactive/__init__.py, diofant/interactive/printing.py, diofant/interactive/session.py, diofant/interactive/tests/test_ipython.py, diofant/interactive/tests/test_ipythonprinting.py, diofant/matrices/matrices.py, docs/install.rst, docs/modules/evalf.rst, docs/modules/integrals/integrals.rst, docs/modules/interactive.rst, docs/modules/matrices/matrices.rst, docs/modules/polys/agca.rst, docs/modules/polys/basics.rst, docs/modules/polys/wester.rst, docs/tutorial/calculus.rst, docs/tutorial/intro.rst, docs/tutorial/matrices.rst, docs/tutorial/simplification.rst, docs/tutorial/solvers.rst
* now run init_printing() on import
* setup here displayhook-related stuff and printing of non-Diofant's  types (e.g. sets)
* sstrrepr now default for Python console, unicode pretty-printing - for IPython
* drop init_ipython_session(), provide low-level tools (AST transformers)
* simplify AutomaticSymbols signature and tests
=> Run printing setup on (interactive) session startup

diofant/core/function.py, diofant/core/symbol.py, diofant/core/tests/test_sympify.py, diofant/functions/elementary/tests/test_piecewise.py, diofant/matrices/matrices.py, diofant/plotting/experimental_lambdify.py, diofant/polys/domains/domain.py, diofant/polys/domains/expressiondomain.py, diofant/polys/domains/modularinteger.py, diofant/polys/domains/mpelements.py, diofant/polys/orderings.py, diofant/polys/polyclasses.py, diofant/polys/rootisolation.py, diofant/printing/defaults.py, diofant/printing/repr.py, diofant/printing/tests/test_dot.py, diofant/printing/tests/test_repr.py
Keep invariant eval(repr(foo)) == foo.
=> Fix repr methods of polys module

diofant/calculus/optimization.py, diofant/core/symbol.py, diofant/functions/elementary/miscellaneous.py, diofant/functions/elementary/tests/test_miscellaneous.py, diofant/polys/numberfields.py, diofant/printing/str.py, diofant/simplify/ratsimp.py, diofant/solvers/inequalities.py, diofant/solvers/solvers.py, diofant/solvers/tests/test_inequalities.py, diofant/solvers/tests/test_solvers.py, diofant/tests/test_wester.py, docs/modules/solvers/solvers.rst, docs/release/notes-0.9.rst, setup.py
=> Further cleanup of solve()

diofant/polys/numberfields.py, diofant/polys/tests/test_numberfields.py, diofant/printing/mathematica.py, diofant/printing/tests/test_mathematica.py, diofant/solvers/tests/test_solvers.py, docs/release/notes-0.9.rst
=> Fix _minpoly_groebner() to work with generic AlgebraicNumber's

diofant/polys/polyoptions.py, diofant/polys/polyroots.py, diofant/polys/polytools.py, diofant/polys/rootoftools.py, diofant/polys/tests/test_rootoftools.py, docs/release/notes-0.9.rst
See also
-------------------
- Maple's [RootOf](http://www.maplesoft.com/support/help/Maple/view.aspx?path=RootOf)
- sympy/sympy#9366
- sympy/sympy#8770
=> Canonicalization of RootOf for algebraic coefficients

diofant/core/__init__.py, diofant/core/add.py, diofant/core/basic.py, diofant/core/mul.py, diofant/core/numbers.py, diofant/core/tests/test_args.py, diofant/core/tests/test_numbers.py, diofant/domains/algebraicfield.py, diofant/polys/numberfields.py, diofant/polys/polyclasses.py, diofant/polys/tests/test_numberfields.py, diofant/printing/mathematica.py, diofant/printing/pretty/pretty.py, diofant/printing/pretty/tests/test_pretty.py, diofant/printing/repr.py, diofant/printing/str.py, diofant/printing/tests/test_mathematica.py, diofant/printing/tests/test_repr.py, diofant/printing/tests/test_str.py, diofant/simplify/tests/test_simplify.py, diofant/tests/test_wester.py, diofant/utilities/tests/test_pickling.py, docs/modules/core.rst, docs/release/notes-0.10.rst, docs/release/notes-0.9.rst
=> Remove old, Expr-derived AlgebraicNumber class

diofant/core/cache.py, diofant/core/tests/test_cache.py, diofant/polys/densebasic.py, diofant/polys/euclidtools.py, diofant/polys/rootisolation.py, diofant/polys/tests/test_densebasic.py, docs/release/notes-0.10.rst, setup.py
=> Drop cachetools deps, use functools.lru_cache

diofant/core/function.py, diofant/core/tests/test_args.py, diofant/core/tests/test_function.py, diofant/core/tests/test_subs.py, diofant/diffgeom/tests/test_diffgeom.py, diofant/printing/latex.py, diofant/printing/pretty/tests/test_pretty.py, diofant/printing/tests/test_latex.py, diofant/series/tests/test_series.py, diofant/simplify/tests/test_cse.py, diofant/simplify/tests/test_trigsimp.py, diofant/solvers/ode.py, diofant/solvers/pde.py, diofant/solvers/tests/test_ode.py, docs/release/notes-0.10.rst
Like https://github.com/sympy/sympy/pull/2613.
In this way, Subs will be more consistent with subs method, which take two scalar argument or one iterable container of pairs.
=> Change Subs interface

diofant/polys/rootisolation.py, diofant/polys/rootoftools.py, diofant/polys/tests/test_rootisolation.py, diofant/polys/tests/test_rootoftools.py, docs/release/notes-0.10.rst
=> Identify imaginary roots for polys

diofant/domains/__init__.py, diofant/domains/algebraicfield.py, diofant/domains/domain.py, diofant/polys/compatibility.py, diofant/polys/densetools.py, diofant/polys/rootisolation.py, diofant/polys/rootoftools.py, diofant/polys/tests/test_densetools.py, diofant/polys/tests/test_rootisolation.py, diofant/polys/tests/test_rootoftools.py, docs/modules/domains.rst, docs/release/notes-0.10.rst
see https://groups.google.com/d/msg/sympy/Ujznd13xfgw/LPaqaWnbr40J
=> Root isolation for polynomials with algebraic coefficients

diofant/domains/domain.py, diofant/domains/field.py, diofant/domains/ring.py, diofant/polys/__init__.py, diofant/polys/compatibility.py, diofant/polys/densearith.py, diofant/polys/euclidtools.py, diofant/polys/factortools.py, diofant/polys/fields.py, diofant/polys/groebnertools.py, diofant/polys/modulargcd.py, diofant/polys/monomials.py, diofant/polys/polyclasses.py, diofant/polys/polyroots.py, diofant/polys/polytools.py, diofant/polys/rings.py, diofant/polys/rootisolation.py, diofant/polys/solvers.py, diofant/polys/sqfreetools.py, diofant/polys/tests/test_modulargcd.py, diofant/polys/tests/test_polyclasses.py, diofant/polys/tests/test_polytools.py, diofant/polys/tests/test_rings.py, diofant/polys/tests/test_sqfreetools.py, diofant/simplify/ratsimp.py, docs/release/notes-0.10.rst
=> Misc fixes

diofant/domains/integerring.py, diofant/domains/tests/test_gmpy.py, diofant/polys/compatibility.py, diofant/polys/factortools.py, diofant/polys/galoistools.py, diofant/polys/rings.py, diofant/polys/sqfreetools.py, diofant/polys/tests/test_galoistools.py, diofant/polys/tests/test_sqfreetools.py, docs/internals/polys.rst, docs/literature.rst, docs/release/notes-0.10.rst
=> Fix #714 (v3)

diofant/integrals/risch.py, diofant/tests/integrals/test_integrals.py, diofant/tests/integrals/test_risch.py, docs/release/notes-0.10.rst
@jksuom, this is an alternative (single line patch) to https://github.com/sympy/sympy/pull/15826.
=> integerals: correct derivation() to return a poly over a field

diofant/polys/rootisolation.py, diofant/tests/polys/test_rootisolation.py
Mostly same approach as [here](https://github.com/diofant/diofant/blob/3c0c949945de691ad16794cf06c2ebc1eaf5ae18/diofant/polys/rootisolation.py#L460-L468) in the `dup_isolate_real_roots_sqf()`.
=> Real roots isolation for non-sqf polynomials over complex algebraic fields

diofant/solvers/ode.py, diofant/tests/solvers/test_ode.py, docs/modules/solvers/ode.rst, docs/release/notes-0.11.rst
=> Inhomogenous case for expm/jordan solver (step 1)

diofant/polys/galoistools.py, diofant/polys/sqfreetools.py, diofant/tests/polys/test_factortools.py, diofant/tests/polys/test_galoistools.py, diofant/tests/polys/test_rings.py, docs/release/notes-0.11.rst, docs/sources.bib
=> Fix polynomial algorithms for FF of non-prime order

diofant/polys/galoistools.py, docs/release/notes-0.11.rst
This is an alternative fix to the problem with dup_gf_Qbasis(),
mentioned in the diofant/diofant#964.
Closes sympy/sympy#18749
=> Drop dup_gf_Qbasis() helper, reuse Matrix.nullspace() code

.github/workflows/test.yml
Since ~20 Feb we have broken version's in the Github Actions artifacts (dist.zip).  This should be fixed before release.
=> Fix broken version in dist.zip

diofant/__init__.py, diofant/domains/__init__.py, diofant/domains/finitefield.py, diofant/domains/integerring.py, diofant/polys/factorization_alg_field.py, diofant/polys/factortools.py, diofant/polys/polyconfig.py, diofant/polys/polyerrors.py, diofant/polys/solvers.py, diofant/tests/polys/test_factorization_alg_field.py, diofant/tests/polys/test_factortools.py, docs/internals/polys.rst, docs/modules/domains.rst, docs/release/notes-0.12.rst
This is a continuation of work in sympy/sympy#2468 and https://github.com/diofant/diofant/pull/712.
Todo:
@katjasophie, I assume, I can use your unmerged yet work from sympy/sympy#2468 to the Diofant on terms of the usual SymPy license.  Please reply, if you are disagreed.
Some benchmarks on my system:
```
In [2]: R, x, y = ring('x, y', QQ.algebraic_field(sqrt(2)))
...: f = (x + y)*(x**2 + sqrt(2)*y)
...: %timeit efactor(f)
...: %timeit f.factor_list()
350 ms ± 3.83 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
226 ms ± 875 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)
In [3]: R, x, y, z = ring('x, y, z', QQ.algebraic_field(root(2, 5)))
...: f = (x - y)*(x**2*y + root(2, 5)*y**2*z)
...: %timeit efactor(f)
...: %timeit f.factor_list()
514 ms ± 12.6 ms per loop (mean ± std. …
```
=> New factorization algorithm for polynomials over algebraic number fields

diofant/calculus/limits.py, diofant/core/function.py, diofant/core/power.py, diofant/functions/elementary/exponential.py, diofant/tests/calculus/test_limits.py, diofant/tests/core/test_function.py, diofant/tests/functions/test_gamma_functions.py
=> calculus: fix handling nested Order() terms in Limit.doit()

pyproject.toml
1. I don't think pip is needed by setuptools to build anything.
2. setuptools uses a [PEP 517](https://peps.python.org/pep-0517/#get-requires-for-build-wheel) hook to add wheel automatically only when building a wheel (and not an sdist), so declaring our own dependency on wheel is unnecessary.
=> Remove pip and wheel build dependencies
